# [Experiment Info]
exp_name: 'v12_compleca' # "v13_q_orth"
seed: 42

# [Model Settings]
model:
  backbone: "intfloat/multilingual-e5-small"
  lora:
    r: 16
    alpha: 32
    dropout: 0.1
  head:
    num_vectors: 2  # Phase 1 실험 땐 1로 바꾸면 됨
    input_dim: 384

# [Training Settings]
train:
  batch_size: 128
  epochs: 20
  lr: 1.0e-3
  warmup_ratio: 0.1

# [Valid Settings]
valid:
  mrr_ratio: 0.8

# [Dataset]
data_path: "data/book_meta.parquet"